'use strict';

// Original summaries of official sources. See SOURCES.md for feature evidence.
globalThis.CAMPUS_PLACES = [
  { id: 'kennedy-study', title: 'Kennedy Library', location: 'Building 35 · Library', description: 'Find quiet or collaborative study areas and a place to settle into your work.', tags: ['quiet', 'group', 'indoor'], source: 'https://library.calpoly.edu/', note: 'Choose the area that suits your work and follow local noise signage. Check the library site for current hours.' },
  { id: 'student-fishbowls', title: 'Library Student Fishbowls', location: 'Building 35 · Level 2', description: 'Reserve an enclosed space for a study group, with a large monitor for shared work.', tags: ['group', 'reservable', 'indoor', 'monitors'], source: 'https://library.calpoly.edu/visit/study-and-meeting-spaces', note: 'Use the student fishbowl reservation link on the official page. Booking limits and available times are managed by the library.' },
  { id: 'dss-study', title: 'Digital Scholarship Studio · 115C', location: 'Building 35 · Level 1, Room 115C', description: 'Meet in a reservable fishbowl for a small-group digital project or research session.', tags: ['group', 'reservable', 'indoor', 'research'], source: 'https://library.calpoly.edu/visit/study-and-meeting-spaces', note: 'Room 115C has student reservations; the neighboring 115D has different booking rules. Check the official reservation page.' },
  { id: 'hub24', title: 'Library Hub24', location: 'Building 35 · Levels 1 and 2', description: 'Study in the library’s extended-hours area, with computer workstations and laptop monitors.', tags: ['late', 'computers', 'indoor', 'monitors'], source: 'https://library.calpoly.edu/visit/study-and-meeting-spaces', note: 'After-hours entry requires an active PolyCard. Check current library access notices; upper-floor books are unavailable during Hub24-only hours.' },
  { id: 'library-courtyard', title: 'Kennedy Library Courtyard', location: 'Building 35 · Level 1 courtyard', description: 'Take your reading into the library’s redesigned courtyard for a change of scenery.', tags: ['outdoors'], source: 'https://www.calpoly.edu/news/light-spacious-and-bustling-take-look-inside-refreshed-kennedy-library', note: 'An outdoor option within the library. Weather, access, seating, and noise vary; check conditions when you arrive.' },
  { id: 'chandler-lounge', title: 'Chandler Study Lounge', location: 'University Union · Building 65', description: 'Settle into a dedicated study lounge in the University Union between classes.', tags: ['indoor'], source: 'https://www.asi.calpoly.edu/facilities/university-union/', note: 'ASI lists this as a study lounge. Check current facility hours and posted room guidance; live noise and seat availability are not tracked here.' },
  { id: 'san-luis-lounge', title: 'San Luis Study Lounge', location: 'University Union · Building 65', description: 'Find a dedicated University Union lounge for a campus study break.', tags: ['indoor'], source: 'https://www.asi.calpoly.edu/facilities/university-union/', note: 'Check ASI for facility hours and current room information. Computer and seating availability can change.' },
  { id: 'uu-lounge', title: 'The Lounge at the UU', location: 'University Union · Building 65, Room 119', description: 'A social space for studying, relaxing, or catching up with friends.', tags: ['group', 'indoor', 'social'], source: 'https://www.asi.calpoly.edu/asi-now/press-releases/discover-the-lounge-at-the-university-union/', note: 'ASI describes this as a recreational study and social space. Events can affect the atmosphere; check current Union information before visiting.' },
  { id: 'uu-plaza', title: 'University Union Plaza', location: 'Outside Building 65 · Central campus', description: 'Choose an outdoor campus setting near the University Union for a break with your notes.', tags: ['outdoors', 'social'], source: 'https://www.asi.calpoly.edu/facilities/university-union/', note: 'The plaza also hosts events. Weather, noise, and available seating vary.' },
  { id: 'uu-common', title: 'University Union Common Areas', location: 'Building 65 · Common seating areas', description: 'Find open seating, Wi-Fi, and charging stations within the University Union.', tags: ['power', 'indoor', 'wifi'], source: 'https://www.asi.calpoly.edu/facilities/university-union/', note: 'Charging stations are a building amenity, not a promise of an outlet at every seat. Check posted access and opening hours.' }
].map(item => ({ ...item, type: 'study', icon: 'book', majors: [], sourceName: item.id.startsWith('uu-') || item.id.includes('lounge') ? 'ASI Cal Poly' : 'Cal Poly Kennedy Library', reviewed: '2026-09-13' }));

globalThis.CAMPUS_RESOURCES = [
  { id: 'tutoring', title: 'Writing & Learning Tutoring', category: 'Learning', description: 'Get help with course questions, writing projects, exam preparation, and study skills.', tags: ['academic', 'tutoring', 'writing', 'math', 'study skills'], source: 'https://writingandlearning.calpoly.edu/tutoring', sourceName: 'Cal Poly Office of Writing and Learning' },
  { id: 'advising', title: 'Academic Advising', category: 'Learning', description: 'Find your advising center and tools for course planning, registration, and academic questions.', tags: ['academic', 'advising', 'registration', 'classes', 'major'], source: 'https://advising.calpoly.edu/', sourceName: 'Cal Poly Academic Advising' },
  { id: 'makerspace', title: 'Mustang Makerspace', category: 'Making', description: 'Explore 3D printing, laser cutting, sewing, and other tools for student projects.', tags: ['making', '3d printing', 'hardware', 'design', 'sewing', 'engineering'], source: 'https://ceng.calpoly.edu/connection/2025/09/new-mustang-makerspace-open-to-all-students/', sourceName: 'Cal Poly College of Engineering', location: 'Bonderson · Building 197', note: 'Check current shop hours and equipment training before visiting. Laser use requires the shop’s safety certification.' },
  { id: 'craft-center', title: 'ASI Craft Center', category: 'Making', description: 'Explore creative classes and studio passes in ceramics, fabric arts, stained glass, and surfboard shaping.', tags: ['making', 'arts', 'ceramics', 'sewing', 'surfboards', 'classes'], source: 'https://www.asi.calpoly.edu/experience/craft-center/', sourceName: 'ASI Cal Poly', note: 'Classes and studio passes may have fees and registration requirements. Follow the official page for current offerings.' },
  { id: 'tech-rental', title: 'Tech Rental & Printing', category: 'Technology', description: 'Follow the library’s official route to technology rental and printing services.', tags: ['technology', 'equipment', 'rental', 'printing', 'computer'], source: 'https://library.calpoly.edu/services/checkout-and-requests', sourceName: 'Cal Poly Library Services', note: 'Choose Explore Tech Services on the official page. Check the current equipment list and loan terms; availability is not tracked here.' },
  { id: 'library-materials', title: 'Library Borrowing & Course Materials', category: 'Learning', description: 'Find books, course reserves, and options for requesting materials from other libraries.', tags: ['academic', 'books', 'textbooks', 'course reserves', 'research'], source: 'https://library.calpoly.edu/services/checkout-and-requests', sourceName: 'Cal Poly Library Services' },
  { id: 'digital-projects', title: 'Digital Scholarship Studio', category: 'Research', description: 'Find research help and peer consultations on data science, design, and interactive mapping.', tags: ['research', 'technology', 'data science', 'design', 'mapping'], source: 'https://library.calpoly.edu/research/digital-scholarship-studio', sourceName: 'Cal Poly Library Services', location: 'Kennedy Library · Level 1' },
  { id: 'career-help', title: 'Career Services', category: 'Careers', description: 'Explore career guidance, employer connections, and tools for your internship or job search.', tags: ['career', 'jobs', 'internships', 'resume', 'interview'], source: 'https://careerservices.calpoly.edu/', sourceName: 'Cal Poly Career Services' },
  { id: 'basic-needs', title: 'Basic Needs Support', category: 'Support', description: 'Find campus routes to food resources, housing support, and financial wellness information.', tags: ['support', 'food', 'housing', 'financial wellness', 'basic needs'], source: 'https://basicneeds.calpoly.edu/', sourceName: 'Cal Poly Basic Needs Initiative' },
  { id: 'drc', title: 'Disability Resource Center', category: 'Support', description: 'Learn how to request accessibility services, accommodations, and study support.', tags: ['support', 'accessibility', 'accommodations', 'disability', 'academic'], source: 'https://drc.calpoly.edu/', sourceName: 'Cal Poly Disability Resource Center' },
  { id: 'lets-talk', title: 'Let’s Talk · Counseling', category: 'Support', description: 'Learn about informal drop-in consultations with a campus mental health provider.', tags: ['support', 'counseling', 'mental health', 'wellbeing'], source: 'https://chw.calpoly.edu/counseling/lets-talk', sourceName: 'Cal Poly Campus Health & Wellbeing', note: 'Check the official page for locations, schedules, and the distinction between informal consultations and ongoing counseling.' },
  { id: 'research-help', title: 'Office of Student Research', category: 'Research', description: 'Find advising and introductory resources for getting started with student research.', tags: ['research', 'academic', 'faculty', 'projects'], source: 'https://studentresearch.calpoly.edu/', sourceName: 'Cal Poly Office of Student Research' },
  { id: 'outdoor-rentals', title: 'Poly Escapes Outdoor Rentals', category: 'Recreation', description: 'Explore gear rentals for outdoor plans, including tents, coolers, and kayaks.', tags: ['recreation', 'outdoors', 'equipment', 'kayaking', 'camping'], source: 'https://www.asi.calpoly.edu/asi-now/asi-blog/plan-your-fall-2026-semester-with-asi/', sourceName: 'ASI Cal Poly', note: 'The official fall guide links to the Poly Escapes Rental Center. Check current rental rates, terms, and equipment availability.' },
  { id: 'asi-space-activity', title: 'ASI Space Activity', category: 'Recreation', description: 'Check ASI’s own activity indicators for selected Union lounges and Recreation Center spaces.', tags: ['recreation', 'study', 'seating', 'university union'], source: 'https://www.asi.calpoly.edu/asi-current-space-activity/', sourceName: 'ASI Cal Poly', note: 'Activity indicators are provided on ASI’s site. This app does not receive or display a live occupancy feed.' }
].map(item => ({ ...item, type: 'resource', icon: 'compass', majors: [], reviewed: '2026-09-13', note: item.note || 'Use the official source to check how to access this service and its current details.' }));

if (typeof module !== 'undefined') module.exports = { places: globalThis.CAMPUS_PLACES, resources: globalThis.CAMPUS_RESOURCES };
