'use strict';

// Source facts are separate from editorial matching tags. See SOURCES.md.
globalThis.OPPORTUNITIES = [
  { id: 'csai', title: 'Computer Science & AI', type: 'club', icon: 'people', description: 'Explore artificial intelligence through workshops, discussions, and collaborative learning.', tags: ['ai', 'software', 'research'], majors: ['computer science', 'software engineering', 'statistics'], source: 'https://csc.calpoly.edu/student-clubs/', sourceName: 'Cal Poly Computer Science & Software Engineering' },
  { id: 'robotics', title: 'Cal Poly Robotics Club', type: 'hands-on', icon: 'gear', description: 'Build robots with a multidisciplinary, project-focused student community.', tags: ['hardware', 'software'], majors: ['mechanical engineering', 'electrical engineering', 'computer engineering'], source: 'https://csc.calpoly.edu/student-clubs/', sourceName: 'Cal Poly Computer Science & Software Engineering' },
  { id: 'surp-engineering', title: 'Engineering Summer Research', type: 'research', icon: 'flask', description: 'Explore faculty-guided summer projects through the College of Engineering SURP.', tags: ['research', 'hardware', 'software'], majors: ['mechanical engineering', 'electrical engineering', 'computer engineering', 'civil engineering', 'biomedical engineering', 'aerospace engineering', 'computer science'], source: 'https://ceng.calpoly.edu/research-innovation/student-research', sourceName: 'Cal Poly College of Engineering' },
  { id: 'innovation-quest', title: 'Innovation Quest', type: 'competition', icon: 'bulb', description: 'Develop an innovative idea or prototype into a venture through this entrepreneurship competition.', tags: ['startups', 'hardware', 'software', 'design'], majors: ['business administration', 'industrial engineering', 'mechanical engineering'], source: 'https://cie.calpoly.edu/prepare/innovation-quest/', sourceName: 'Cal Poly Center for Innovation & Entrepreneurship' },
  { id: 'security', title: 'CP Security Education Club', type: 'club', icon: 'shield', description: 'Explore cybersecurity, hacking, and protecting computers and information systems.', tags: ['cybersecurity', 'software'], majors: ['computer science', 'computer engineering', 'software engineering'], source: 'https://csc.calpoly.edu/student-clubs/', sourceName: 'Cal Poly Computer Science & Software Engineering' },
  { id: 'hack4impact', title: 'Hack4Impact Cal Poly', type: 'club', icon: 'code', description: 'Develop software for local nonprofits alongside a multidisciplinary student team.', tags: ['software', 'design', 'service'], majors: ['computer science', 'software engineering', 'graphic communication'], source: 'https://csc.calpoly.edu/student-clubs/', sourceName: 'Cal Poly Computer Science & Software Engineering' },
  { id: 'hatchery', title: 'The Hatchery', type: 'startup', icon: 'bulb', description: 'Explore entrepreneurship with workshops, mentorship, and a community building student-led startups.', tags: ['startups', 'design'], majors: ['business administration', 'economics', 'industrial engineering'], source: 'https://cie.calpoly.edu/prepare/hatchery/', sourceName: 'Cal Poly Center for Innovation & Entrepreneurship' },
  { id: 'mustangjobs', title: 'MustangJobs Internship Search', type: 'internship', icon: 'briefcase', description: 'Find Cal Poly’s official route to internship listings and job-search resources.', tags: ['internships', 'software', 'hardware', 'startups', 'research', 'design'], majors: ['computer science', 'business administration', 'biology', 'psychology', 'architecture', 'agricultural business', 'communication studies'], source: 'https://careerservices.calpoly.edu/explore-services/resource-toolkit/job-search', sourceName: 'Cal Poly Career Services', note: 'This is an internship search resource, not a specific vacancy. MustangJobs requires your own Cal Poly sign-in on the official site.' },
  { id: 'wish', title: 'Women Involved in Software & Hardware', type: 'club', icon: 'people', description: 'Connect through mentoring, industry talks, and a community around computing.', tags: ['software', 'hardware'], majors: ['computer science', 'computer engineering', 'electrical engineering'], source: 'https://csc.calpoly.edu/student-clubs/', sourceName: 'Cal Poly Computer Science & Software Engineering' },
  { id: 'ux', title: 'Cal Poly UX Club', type: 'club', icon: 'people', description: 'Explore human-computer interaction with students across disciplines.', tags: ['design', 'software', 'research'], majors: ['psychology', 'communication studies', 'graphic communication', 'art and design', 'computer science'], source: 'https://csc.calpoly.edu/student-clubs/', sourceName: 'Cal Poly Computer Science & Software Engineering' },
  { id: 'games', title: 'Cal Poly Game Development', type: 'club', icon: 'code', description: 'Find a community focused on game development and advocacy.', tags: ['games', 'software', 'design'], majors: ['computer science', 'software engineering', 'art and design'], source: 'https://csc.calpoly.edu/student-clubs/', sourceName: 'Cal Poly Computer Science & Software Engineering' },
  { id: 'computing-research', title: 'Computing Research Society', type: 'club', icon: 'flask', description: 'Connect with peers to explore computing research and share project ideas.', tags: ['research', 'software', 'ai'], majors: ['computer science', 'software engineering', 'statistics'], source: 'https://csc.calpoly.edu/student-clubs/', sourceName: 'Cal Poly Computer Science & Software Engineering' },
  { id: 'slo-hacks', title: 'SLO Hacks', type: 'competition', icon: 'code', description: 'Explore hackathons and workshops that bring student builders together.', tags: ['software', 'design', 'startups'], majors: ['computer science', 'software engineering', 'computer engineering'], source: 'https://csc.calpoly.edu/student-clubs/', sourceName: 'Cal Poly Computer Science & Software Engineering' },
  { id: 'student-research', title: 'Office of Student Research', type: 'research', icon: 'flask', description: 'Start exploring student research through advising and introductory learning resources.', tags: ['research'], majors: ['biology', 'chemistry', 'physics', 'mathematics', 'psychology', 'sociology', 'english', 'history', 'nutrition', 'animal science', 'architecture', 'political science'], source: 'https://studentresearch.calpoly.edu/', sourceName: 'Cal Poly Office of Student Research', note: 'A starting point for finding research, not an advertised project vacancy.' },
  { id: 'business-surp', title: 'Business Summer Research', type: 'research', icon: 'flask', description: 'Explore faculty-mentored business research in topics such as analytics, sustainability, and entrepreneurship.', tags: ['research', 'ai', 'startups', 'sustainability'], majors: ['business administration', 'economics', 'statistics'], source: 'https://orfalea.calpoly.edu/undergraduate-programs/summer-undergraduate-research-program', sourceName: 'Cal Poly Orfalea College of Business' },
  { id: 'cla-surp', title: 'Liberal Arts Summer Research', type: 'research', icon: 'flask', description: 'Explore mentor-led scholarship and creative activities through the College of Liberal Arts SURP.', tags: ['research', 'design'], majors: ['psychology', 'sociology', 'english', 'history', 'communication studies', 'art and design', 'political science'], source: 'https://cla.calpoly.edu/research-innovation/research-surp', sourceName: 'Cal Poly College of Liberal Arts' },
  { id: 'research-competition', title: 'Research & Creative Activity Competition', type: 'competition', icon: 'flask', description: 'Explore Cal Poly’s route to presenting research and creative work in the CSU competition.', tags: ['research', 'design'], majors: ['biology', 'chemistry', 'physics', 'psychology', 'history', 'english', 'computer science', 'art and design'], source: 'https://studentresearch.calpoly.edu/csu-research-competition', sourceName: 'Cal Poly Office of Student Research' },
  { id: 'career-fairs', title: 'Career Fairs & Employer Events', type: 'internship', icon: 'briefcase', description: 'Explore Career Services events to meet employers and learn about internships.', tags: ['internships', 'software', 'hardware', 'startups', 'research', 'design'], majors: ['business administration', 'computer science', 'mechanical engineering', 'civil engineering', 'agricultural business', 'architecture'], source: 'https://careerservices.calpoly.edu/career-fairs-schedule', sourceName: 'Cal Poly Career Services', note: 'An employer-discovery resource, not a promise of an available internship. Check the official schedule for current events.' }
].map(item => ({ ...item, reviewed: '2026-09-12' }));

// Keep the original discoveries in place while joining their official profiles.
// Directory IDs prevent the same organization appearing twice under different names.
(function () {
  const directory = typeof module !== 'undefined' ? require('./club-data.js') : globalThis.CLUB_DIRECTORY;
  const matcher = typeof module !== 'undefined' ? require('./matcher.js') : globalThis.OpportunityMatcher;
  const overlaps = { csai: '325114', security: '325037', hack4impact: '324986', wish: '324517', games: '325035' };
  if (!matcher?.validData(directory) || Object.values(overlaps).some(id => !directory.some(item => item.directoryId === id))) {
    globalThis.OPPORTUNITIES = null;
    return;
  }
  const used = new Set(Object.values(overlaps));
  globalThis.OPPORTUNITIES = [
    ...globalThis.OPPORTUNITIES.map(item => {
      const profile = directory.find(club => club.directoryId === overlaps[item.id]);
      return profile ? { ...item, directoryId: profile.directoryId, directoryTitle: profile.title, source: profile.source, sourceName: profile.sourceName } : item;
    }),
    ...directory.filter(item => !used.has(item.directoryId))
  ];
})();

if (typeof module !== 'undefined') module.exports = globalThis.OPPORTUNITIES;
